files:
  - source: /android/app/src/main/res/values/strings.xml
    translation: /android/app/src/main/res/values-%two_letters_code%/strings.xml
  - source: /locales/languages/en.json
    translation: /locales/languages/%locale%.json
